name: 'ðŸ—‘ï¸ DNS Deleter'

on:
  workflow_dispatch:
    inputs:
      record_type:
        description: 'Tipe Record yang akan dihapus (A, CNAME, dll)'
        required: true
      record_name:
        description: "Nama Subdomain ('@' untuk root domain)"
        required: true

jobs:
  delete-record:
    runs-on: ubuntu-latest
    steps:
      - name: '1. Checkout Kode'
        uses: actions/checkout@v4
      - name: '2. Setup Python'
        uses: actions/setup-python@v5
      - name: '3. Install Dependencies'
        run: pip install requests
      - name: '4. Eksekusi Skrip DNS Deleter'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: >
          python dns_manager.py delete
          --type "${{ github.event.inputs.record_type }}" 
          --name "${{ github.event.inputs.record_name }}"
