name: 'ðŸ•¹ï¸ DNS Manager (Create / Update)'

on:
  workflow_dispatch:
    inputs:
      record_type:
        description: 'Tipe Record (A, AAAA, CNAME, TXT, MX)'
        required: true
        default: 'A'
      record_name:
        description: "Nama Subdomain ('@' untuk root domain)"
        required: true
        default: 'www'
      record_content:
        description: 'Konten Record (IP Address, domain, teks, dll)'
        required: true

jobs:
  manage-record:
    runs-on: ubuntu-latest
    steps:
      - name: '1. Checkout Kode'
        uses: actions/checkout@v4
      - name: '2. Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: '3. Install Dependencies'
        run: pip install requests
      - name: '4. Eksekusi Skrip DNS Manager'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: >
          python dns_manager.py update 
          --type "${{ github.event.inputs.record_type }}" 
          --name "${{ github.event.inputs.record_name }}" 
          --content "${{ github.event.inputs.record_content }}"
